### PR TITLE
feat(helm): initialize helm chart

### PR DESCRIPTION
**Pull request by oliverbaehler**
This adds the helm chart plus relevant github workflows. The Chart is released as OCI package on the repository. You also get a signature (CoSign) + SLSA 3 Attestation.

What's special: you can place the crds in the crd folder. This is not managed by helm but by the chart itself. This way you can manage CRDs with the chart beyond the first install

Let me know if you have any questions. 

You should probably also build a workflow to release the docker image on tag... let me know if you need help with that.

### CODE REVIEW

**Comment by gianlucam76** [comment]
This looks great @oliverbaehler. Thank you. 

If a new release changes one CRDs or resources, is there a make target to update the chart?

**Comment by gianlucam76** [comment]
@all-contributors
please add @oliverbaehler  for <contributions>.

**Comment by gianlucam76** [comment]
@all-contributors
please add @oliverbaehler  for code.

**Comment by oliverbaehler** [comment]
> This looks great @oliverbaehler. Thank you.
> 
> If a new release changes one CRDs or resources, is there a make target to update the chart?

We can make a copy target. However that has to be done before merging to the main branch, we can't do that in a workflow (easily)

**Comment by gianlucam76** [comment]
> > This looks great @oliverbaehler. Thank you.
> > If a new release changes one CRDs or resources, is there a make target to update the chart?
> 
> We can make a copy target. However that has to be done before merging to the main branch, we can't do that in a workflow (easily)

Thank you. What you have is already great and enough. No need to add more. 

Would you mind looking at CI failure? It appears a typo to me. make target is using "./.github/configs/ct.yaml" but I see we have "./.github/config/ct.yaml"

**Comment by oliverbaehler** [comment]
closes #59

**Comment by gianlucam76** [comment]
@oliverbaehler sorry to bug, the test chart failed again. When you get a chance can you please take a look. 

PS: there are already folks who want to deploy it using helm chart! So thanks again for adding this option!

**Pull request merged**
